### cars index
GET http://localhost:3000/cars.json

### cars create
POST http://localhost:3000/cars.json
Content-Type: application/json

{
  "input_make": "Test",
  "input_model": "Test",
  "input_year": "Test",
  "input_price": 0,
  "input_color": "Test"
}

### cars show 
GET http://localhost:3000/cars/4.json

### cars update
PATCH http://localhost:3000/cars/3.json
Content-Type: application/json

{
  "make": "Honda",
  "model": "Civic",
  "year": "1999",
  "price": 5000,
  "color": "green"
}

### cars destroy
DELETE http://localhost:3000/cars/5.json